### ISSUE TITLE
Apply the Beman Standard to beman.exemplar

### ISSUE THREAD

**Issue by neatudarius** [beman-project/exemplar#14]
Apply the [Beman Standard]( https://github.com/beman-project/beman/blob/main/docs/BEMAN_STANDARD.md) to Beman.Example and possible more more tweaks.

----------
# Updates related to the Beman Standard:
## License
- [x] LICENSE.APPROVED
- [x] LICENSE.APACHE_LLVM
- [x] LICENSE.CRITERIA
 
## General

- [x] LIBRARY.NAMES
- [x] REPOSITORY.NAME
- [x] REPOSITORY.CODEOWNERS

## Top-level

- [x] TOPLEVEL.CMAKE
- [x] TOPLEVEL.LICENSE
- [x] TOPLEVEL.README

## README.md

- [x] README.TITLE
- [x] README.PURPOSE
- [x] README.IMPLEMENTS

## CMake

- [x] CMAKE.DEFAULT
- [x] CMAKE.PROJECT_NAME
- [x] CMAKE.LIBRARY_NAME
- [x] CMAKE.LIBRARY_ALIAS
- [x] CMAKE.TARGET_NAMES
- [ ] CMAKE.CONFIG
- [x] CMAKE.SKIP_TESTS
- [x] CMAKE.AVOID_PASSTHROUGHS

## Directory Layout

- [x] DIRECTORY.INTERFACE_HEADERS
- [x] DIRECTORY.IMPLEMENTATION_HEADERS
- [x] DIRECTORY.SOURCES
- [ ]  DIRECTORY.TESTS
- [ ]  DIRECTORY.EXAMPLES
- [ ]  DIRECTORY.DOCS
- [ ]  DIRECTORY.PAPERS

## File contents

- [ ]  FILE.NAME
- [ ] FILE.TEST_NAMES
- [x] FILE.LICENSE_ID
- [x] FILE.COPYRIGHT

## C++

- [x] CPP.NAMESPACE

# Updates related to docs and usage example:
- [x] Add API example
- [x] Add basic unit test and framework integration with Gtest.
- [x] Add usage example in `examples/`

# Updates related to CI/infrastructure
- [x] Compiler support on CI
- [x] Add `.gitignore`.
- [x] Add `.github/CODEOWNERS`.
- [x] Add badge with CI tests status in `README.md`.

**Comment by neatudarius** [comment]
Most of the issues are implemented in #15

**Comment by bretbrownjr** [comment]
@neatudarius Can you go through the checklist and mark off what's resolved?

**Comment by neatudarius** [comment]
@bretbrownjr , not the list is updated. I'll put the test naming convention on next sync agenda, and then create PR with missing bits.
