### ISSUE TITLE
Use CMake Header File Sets

### ISSUE THREAD

**Issue by bretbrownjr** [beman-project/exemplar#21]
The exemplar project should be using the CMake Header FILE_SET feature instead of separate include directories and install logic for headers.

Using CMake header file sets provides a more organized, maintainable, and modern approach to managing header files. It aligns with the target-based paradigm of modern CMake, reduces the need for manual commands, and makes the intent of the CMake configuration clearer.

**Mentor Available**: @bretbrownjr

**Comment by wusatosi** [comment]
I am interested in taking this!
Is there any pointers you could provide for existing example uses of FILE_SET?

**Comment by bretbrownjr** [comment]
[We used to use FILE_SETs](https://github.com/beman-project/exemplar/blob/3742e5021413b55b1c77a2e3764b46e111ee6648/src/example/CMakeLists.txt#L11-L18). I'm unclear why it was removed. @neatudarius might have thoughts?

@wusatosi, when implementing this, mostly make sure that everything builds as expected and a `cmake --install` workflow installs the header files as expected.

If you want to go beyond what I had before, it does make sense to set [`VERIFY_INTERFACE_HEADER_SETS`](https://cmake.org/cmake/help/latest/prop_tgt/VERIFY_INTERFACE_HEADER_SETS.html) and build the `all_verify_interface_header_sets` CMake target. This will ensure each header builds correctly on its own. That CMake feature will require CMake 3.24, though.
