### ISSUE TITLE
Define `.clang-format` or equivalent

### ISSUE THREAD

**Issue by wusatosi** [beman-project/exemplar#29]
`.clang-format` file defines the formatting rule for cpp files and allow modern tool chain to lint & auto-format 

This file has already been defined for [Optional26](https://github.com/beman-project/Optional26/blob/main/.clang-format) and [net29](https://github.com/beman-project/net29/blob/main/.clang-format) (note: those files are equivalent in terms of content).

**Comment by camio** [comment]
This is a good idea.

**Comment by wusatosi** [comment]
> This is a good idea.

I am interested in setting up clang-format linters and auto formatting prs, I cannot move forward without a `.clang-format` file. Should I just pull the `.clang-format` config from those two projects for now and leave this issue open?

**Comment by neatudarius** [comment]
> > This is a good idea.
> 
> I am interested in setting up clang-format linters and auto formatting prs, I cannot move forward without a `.clang-format` file. Should I just pull the `.clang-format` config from those two projects for now and leave this issue open?

Yes, pleae pull the one from optional26 repo. I think @steve-downey revised that file in https://github.com/beman-project/optional26/pull/52 and it's up to date.

**Comment by wusatosi** [comment]
> > > This is a good idea.
> > 
> > 
> > I am interested in setting up clang-format linters and auto formatting prs, I cannot move forward without a `.clang-format` file. Should I just pull the `.clang-format` config from those two projects for now and leave this issue open?
> 
> Yes, pleae pull the one from optional26 repo. I think @steve-downey revised that file in [beman-project/optional26#52](https://github.com/beman-project/optional26/pull/52) and it's up to date. Please check his PR and see what logic can be reused. I think optional26 may be ahead of other repos in Beman project, so I would like to get what is good there, and put in exemplar.

The update to `.clang-format` you mentioned in the pr apply to formatting the paper, [link to change](https://github.com/beman-project/optional26/pull/52/files#diff-b04bdd3f05173dc1e664b2c875d26852dda7a3c7538f96ab581a6bb80ae6dcc8) . I presume you mean pull the `.clang-format` from the root directory? (File: [link](https://github.com/beman-project/optional26/blob/main/.clang-format), last updated one year ago on [this commit](https://github.com/beman-project/optional26/commit/89655ed7eabce2b079f30939d84f69b8e1036a5c)?

**Comment by neatudarius** [comment]
> > > > This is a good idea.
> > > 
> > > 
> > > I am interested in setting up clang-format linters and auto formatting prs, I cannot move forward without a `.clang-format` file. Should I just pull the `.clang-format` config from those two projects for now and leave this issue open?
> > 
> > 
> > Yes, pleae pull the one from optional26 repo. I think @steve-downey revised that file in [beman-project/optional26#52](https://github.com/beman-project/optional26/pull/52) and it's up to date. Please check his PR and see what logic can be reused. I think optional26 may be ahead of other repos in Beman project, so I would like to get what is good there, and put in exemplar.
> 
> The update to `.clang-format` you mentioned in the pr apply to formatting the paper, [link to change](https://github.com/beman-project/optional26/pull/52/files#diff-b04bdd3f05173dc1e664b2c875d26852dda7a3c7538f96ab581a6bb80ae6dcc8) . I presume you mean pull the `.clang-format` from the root directory? (File: [link](https://github.com/beman-project/optional26/blob/main/.clang-format), last updated one year ago on [this commit](https://github.com/beman-project/optional26/commit/89655ed7eabce2b079f30939d84f69b8e1036a5c)?

ooohh, I had the impresion the .clang-format file from root directory (main) was also updated. @steve-downey , what you would adivice here? TLDR: we need .clang-format file up to date to be promoted in exemplar repo (and then in all repos in Beman).

**Comment by camio** [comment]
The .clang-format used in optional26 looks very hand crafted. I think we should use [this .clang-format](https://github.com/llvm/llvm-project/blob/main/.clang-format) as I mentioned [here](https://github.com/beman-project/exemplar/issues/27#issuecomment-2374672538).

**Comment by steve-downey** [comment]
The LLVM style is terribly idiosyncratic and only easy to get at because clang-format is an LLVM project.

**Comment by camio** [comment]
> The LLVM style is terribly idiosyncratic

IMO the same can be said about *any* style, which is why the engineering argument is compelling: the LLVM style is the best supported. I don't think actively maintaining a `.clang-format` that looks like the standard is where our time should be spent (See [[CORE.INDUSTRY_STANDARD]](https://github.com/beman-project/beman/blob/7016bcc42096527d6b23f4828a77ae745247d6aa/docs/beman-standard.md?plain=1#L23-L25)). That being said, my opinion is for only beman.exemplar; other Beman projects should be free to choose different styles.

**Comment by neatudarius** [comment]
> > The LLVM style is terribly idiosyncratic
> 
> IMO the same can be said about _any_ style, which is why the engineering argument is compelling: the LLVM style is the best supported. I don't think actively maintaining a `.clang-format` that looks like the standard is where our time should be spent (See [[CORE.INDUSTRY_STANDARD]](https://github.com/beman-project/beman/blob/7016bcc42096527d6b23f4828a77ae745247d6aa/docs/beman-standard.md?plain=1#L23-L25)). That being said, my opinion is for only beman.exemplar; other Beman projects should be free to choose different styles.

I would really want to have the same .clang-format file in all repos. My wish would be to move such tooling (linting, CI support etc), as much as possible, into a new repo / git submodule, and be able to reuse everywhere in Beman! 

My preference would be to use a default config - e.g., LLVM style  - and have fewer entrie/exceptions in the file.

I will add this topic on next sync agenda.

**Comment by wusatosi** [comment]
> > > The LLVM style is terribly idiosyncratic
> > 
> > 
> > IMO the same can be said about _any_ style, which is why the engineering argument is compelling: the LLVM style is the best supported. I don't think actively maintaining a `.clang-format` that looks like the standard is where our time should be spent (See [[CORE.INDUSTRY_STANDARD]](https://github.com/beman-project/beman/blob/7016bcc42096527d6b23f4828a77ae745247d6aa/docs/beman-standard.md?plain=1#L23-L25)). That being said, my opinion is for only beman.exemplar; other Beman projects should be free to choose different styles.
> 
> I would really want to have the same .clang-format file in all repos. My wish would be to move such tooling (linting, CI support etc), as much as possible, into a new repo / git submodule, and be able to reuse everywhere in Beman!
> 
> My preference would be to use a default config - e.g., LLVM style - and have fewer entrie/exceptions in the file.
> 
> I will add this topic on next sync agenda.

This doesn't sound that much like a good idea?
1. Lint files could get bloated up easily for special cases after special cases or custom config. 
2. Tweaking small sections of lint files for specific projects do sometimes make sense.
3. As long as the default format is sane, it is fine for formatting to be behind the standard.
4. Updating formatting files sometimes require mass refactoring, which makes merging/ git blame a pain and would be best to keep in minimal, syncing format files across multiple projects increase the chance of this happening.

But definitely a good subject to chat at next sync!

**Comment by wusatosi** [comment]
Hey I just made a pr #34, with the cpp code in this project formatted against the standard from optional/ net repo. Take a look and comment if we need to change anything.

**Comment by JeffGarland** [comment]
> Hey I just made a pr #34, with the cpp code in this project formatted against the standard from optional/ net repo. Take a look and comment if we need to change anything.

Have a look at @wusatosi PR.  I noted at least one weird format change it made in the rather small code base from the exemplar. It looks to be easy enough to mitigate with some white space though. 

https://github.com/beman-project/exemplar/pull/34

My experience with clang-format is that the rules are very fiddly and that I didn't like any of the provided base formats.  That's partially because we have different internal formats and partially bc of complex behaviors.  For sure if you write monadic chains -- well lets just say those need to be excluded from formatting bc it was simply awful with everything I tried.

**Comment by camio** [comment]
> My experience with clang-format is that the rules are very fiddly and that I didn't like any of the provided base formats.

Can we move discussion of the relative merits of different .clang-format styles to the [discourse thread](https://discourse.bemanproject.org/t/what-clang-format-config-should-we-adopt/225)? It'd be good to get all these comments in one place.

**Comment by wusatosi** [comment]
#34 is ready for review, would recommend posting `.clang-format` related discussions here.
