### ISSUE TITLE
gtest and gmock are inadvertantly installed using older versions of CMake

### ISSUE THREAD

**Issue by camio** [beman-project/exemplar#32]
[`FechContent`](https://cmake.org/cmake/help/latest/module/FetchContent.html)'s `EXCLUDE_FROM_ALL` keyword in CMake 3.30+ has the impact of ignoring `install` commands in the dependency project. However, this behavior does not manifest in earlier CMake versions which results in exemplar's gtest dependency being installed when CMake's install target is executed.

CMake 3.30 came out recently ([July 2024](https://github.com/Kitware/CMake/releases/tag/v3.30.0)), so forcing users to upgrade to use beman.exemplar is a bit much to ask.

My suggested fix is to set [`INSTALL_GTEST`](https://github.com/google/googletest/blob/6dae7eb4a5c3a169f3e298392bff4680224aa94a/CMakeLists.txt#L20) to `FALSE` using a [`block`](https://cmake.org/cmake/help/latest/command/block.html) that contains the `FetchContent` call.

**Comment by wusatosi** [comment]
So the only thing we need to do is to surround the `FetchContent` with a `block` and unset the `INSTALL_GTEST` option?

**Comment by camio** [comment]
Yep, that's my understanding.

**Comment by wusatosi** [comment]
> Yep, that's my understanding.

Alright, I can take this.

**Comment by camio** [comment]
Awesome! Thanks.

**Comment by wusatosi** [comment]
> Awesome! Thanks.

`block` is introduced in 3.25, should we will need to increase the minimum cmake version again.
