### ISSUE TITLE
Examples should not `return 0;` from main

### ISSUE THREAD

**Issue by camio** [beman-project/exemplar#33]
From [cppreference](https://en.cppreference.com/w/cpp/language/main_function):

> The body of the main function does not need to contain the [return statement](https://en.cppreference.com/w/cpp/language/return): if control reaches the end of main without encountering a return statement, the effect is that of executing return 0;.

This change improves readability by omitting needless code.

**Comment by tzlaine** [comment]
I function that returns an int, should *return an int*.  Just sayin'.  Some of us suffer from ACOD (Acquired Code Obsessive Disorder) about these things.

**Comment by tzlaine** [comment]
Also, get off my lawn.

**Comment by bretbrownjr** [comment]
Yeah, someone write an ISO paper so `void main() {}` does what you'd think.

**Comment by camio** [comment]
I don't think an ISO paper is appropriate for this. How about Twitter? https://x.com/david_sankel/status/1840180977546539145

**Comment by bretbrownjr** [comment]
My usual habit is to immediately call `mynamespace::run`. `main` has an awkward API for a few reasons, which makes it not very configurable or testable. That's my habit for real code anyway. Test cases may benefit from being more terse. Depending.

Regardless, if we want a specific rule for this question, we should write a specific check to enforce it. Human reviewers should focus on matters of good design, taste, software engineering, etc.

**Comment by wusatosi** [comment]
I have an alternative! 

We should just switch to `void main()`!

**Comment by vinniefalco** [comment]
ahem... https://en.cppreference.com/w/c/program/EXIT_status

**Comment by camio** [comment]
I've since been convinced that an explicit `return 0;` is preferrable to implicit.

- The Twitter poll (at 346 votes) indicated 65% prefer explicit and 24% prefer implicit with several experts chiming in in-favor of explicit.
- Examples are for non-experts and the idiosyncratic implicit `return 0` behavior of `main()` is unobvious and frequently not known by C++ developers. I realized that I didn't learn about this behavior until several years of my own C++ journey.

**Comment by wusatosi** [comment]
> I've since been convinced that an explicit `return 0;` is preferrable to implicit.
> 
> * The Twitter poll (at 346 votes) indicated 65% prefer explicit and 24% prefer implicit with several experts chiming in in-favor of explicit.
> * Examples are for non-experts and the idiosyncratic implicit `return 0` behavior of `main()` is unobvious and frequently not known by C++ developers. I realized that I didn't learn about this behavior until several years of my own C++ journey.

yey twitter democracy.

I guess its time to close the issue? @camio
