### ISSUE TITLE
There should be some notification mechanism when scheduled build-test ci fails

### ISSUE THREAD

**Issue by wusatosi** [beman-project/exemplar#36]
Scheduled build-and-test introduced in #28 is triggering correctly.
But failure to routine build-and-test can be silent, e. g. https://github.com/beman-project/exemplar/actions/runs/11109516669 .
(technically GitHub pushes a notification to the latest person that edited cron syntax, but this is clearly insufficient).

There needs to be some notification mechanism to notify the project owner/ contributors that the latest build-and-test fails.

Opening a GitHub issue should be sufficient enough?

**Comment by camio** [comment]
> Opening a GitHub issue should be sufficient enough?

That sounds reasonable to me. Is there risk that a flood of new issues will be generated?

**Comment by wusatosi** [comment]
> [Opening GitHub Issue] sounds reasonable to me. Is there risk that a flood of new issues will be generated?

I can set it up so that there will be a maximum of 1 issue regarding this being open.
