### ISSUE TITLE
Review dog failing in CI due to insufficient permission 

### ISSUE THREAD

**Issue by wusatosi** [beman-project/exemplar#49]
Review dog is not generating reviews correctly.

Error report:

```
reviewdog: This GitHub Token doesn't have write permission of Review API [1],
so reviewdog will report results via logging command [2] and create annotations similar to
github-pr-check reporter as a fallback.
```

See: 
![image](https://github.com/user-attachments/assets/7fa26248-5dfa-45d0-92ad-e1cfc2c2df04)
Link:
https://github.com/beman-project/exemplar/actions/runs/11411570352/job/31756057258?pr=48#step:7:238

CC: @linusboehm

**Comment by wusatosi** [comment]
Potentially a simple fix?
See: https://github.com/reviewdog/action-eslint/issues/148#issuecomment-1282861097

**Comment by wusatosi** [comment]
Would be nice to bundle fix for:
`time=2024-10-18T22:06:15.765Z level=WARN msg="reviewdog: -fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead. See also https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md"`

See: https://github.com/beman-project/exemplar/actions/runs/11411671176/job/31756356511?pr=48#step:7:235

**Comment by wusatosi** [comment]
Open this back up as issue was not resolved correctly.

**Comment by wusatosi** [comment]
Forwarding what @linusboehm commented at https://github.com/beman-project/exemplar/pull/50#issuecomment-2423526878

> this might be the reason: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job
>>  if the workflow was triggered by a pull request from a forked repository, and the Send write tokens to workflows from pull requests setting is not selected, the permissions are adjusted to change any write permissions to read only.
> 
> @camio so seems like a setting change is required (member of the org is not sufficient, as I can't access the settings)

Note we will need to document this in README in case forking doesn't copy-over the permission settings.

**Comment by wusatosi** [comment]
@neatudarius darius, I didn't find the exact setting mentioned in the GitHub docs.
In my personal repos, there seem to be this switch under `setting -> actions -> general`
![image](https://github.com/user-attachments/assets/f1fb4856-bea7-43db-8d7b-49b618bfab22)

Can you check if it's sets to "read and write permissions"?

**Comment by wusatosi** [comment]
> [Updated Permission]

Let me try to update #53 to see.

**Comment by wusatosi** [comment]
Maybe try enable `Allow GitHub Actions to create and approve pull requests`?  Sounds like approve PR and review PR might have overlapping permission?

**Comment by neatudarius** [comment]
`Allow GitHub Actions to create and approve pull requests` - temporary enabled this

**Comment by wusatosi** [comment]
> `Allow GitHub Actions to create and approve pull requests` - temporary enabled this

Looks like it's still not fixed via rerun action. 
Maybe the token's permission isn't refreshed? 
I am going to trigger it again later by updating to the underlying PR.

**Comment by neatudarius** [comment]
Actions seem to work - check this new PR https://github.com/beman-project/exemplar/pull/56.

**Comment by wusatosi** [comment]
> Actions seem to work - check this new PR https://github.com/beman-project/exemplar/pull/56. Maybe you should try to create a new test PR?

#56 is working as expected because there's no linting error to report on. 

I can try, I suspect it's not working because the PR comes from a fork.

**Comment by wusatosi** [comment]
So my working theory is that review dog isn't trigger due to the pull request coming from a fork, in the GitHub docs, there seem to be a difference between PR within a repo and PR from a fork.

Thus I opened #58, but weirdly, the pull request event isn't trigger at all now....

**Comment by wusatosi** [comment]
New progress:

The default `GITHUB_TOKEN` has only read access on pull requests from forked repos, see: [link](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

Maybe changing the trigger to `pull_request_target` would solve this??

**Comment by wusatosi** [comment]
> New progress:
> 
> The default `GITHUB_TOKEN` has only read access on pull requests from forked repos, see: [link](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).
> 
> Maybe changing the trigger to `pull_request_target` would solve this?? 

Confirmed in a testing org. 
But found more weirdness with pre-commit.

**Comment by neatudarius** [comment]
Can I help you?

**Comment by wusatosi** [comment]
> Can I help you?

I think I will add a pr that just fixes this permission issue.

It seems pre-commit sometimes doesn't fail in CI and reports no changes to be made. While with the same parameters running locally will produce a fix.

**Comment by wusatosi** [comment]
> Can I help you?

See #69 for fix.

**Comment by neatudarius** [comment]
> > Can I help you?
> 
> See #69 for fix.

Cool. Let's see what's the status after you merge it! LGTM!
