### ISSUE TITLE
Do only include(CTest) if dashboard is needed

### ISSUE THREAD

**Issue by ClausKlein** [beman-project/exemplar#60]
See https://cmake.org/cmake/help/latest/manual/ctest.1.html

**Comment by camio** [comment]
We're currently using `include(CTest)` to allow for configuration using the `BUILD_TESTING` variable. Is it better to not do this?

**Comment by ClausKlein** [comment]
Yes, see https://github.com/beman-project/execution26/pull/55/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
for some reasons.

**Comment by camio** [comment]
@ClausKlein I don't understand what you're attempting to communicate by pointing me to that diff. It looks like that change removed the ability for someone to turn on tests and examples for that dependency which is an important use-case to support.

**Comment by ClausKlein** [comment]
As a standalone project, testing and installing is always available.

But if I add project with  [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html#id5), I do not want to run its tests or compile the examples!

Even more, sometimes **I don't want to install it**, witch may be excluded with the **EXCLUDE_FROM_ALL** option.

from [Chapter 40. Making Projects Consumable](https://crascit.com/professional-cmake/):

40.2. Don’t Assume A Top Level Build

Many projects have never considered the use case of being absorbed into a larger parent build directly. For such projects, there are a few common problems that are often encountered. The first and perhaps most prevalent is the use of global path variables like CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR. When the project is absorbed into a larger parent build, the relative location of the global path variables will change. The project might then no longer find things at the locations it expected. In general, avoid using CMAKE_SOURCE_DIR or CMAKE_BINARY_DIR unless a path truly needs to be relative to the top level of the source or build tree, even when absorbed into a larger parent build. Prefer instead to use directory-relative variables like CMAKE_CURRENT_SOURCE_DIR and CMAKE_CURRENT_BINARY_DIR, or project-relative variables like PROJECT_SOURCE_DIR and PROJECT_BINARY_DIR.

Another common problem is modifying variables that have the potential to affect the whole build, not just the project. A classic example is forcing the value of cache variables like BUILD_SHARED_LIBS, **BUILD_TESTING**, CMAKE_BUILD_TYPE, CMAKE_MODULE_PATH or CMAKE_RUNTIME_OUTPUT_DIRECTORY. Using the FORCE or INTERNAL keywords with the set() command on these variables prevents a parent project from overriding that choice. Quite often, these variables shouldn’t be defined by the project as cache variables at all, and maybe shouldn’t even be set by the project to begin with. For variables like CMAKE_MODULE_PATH, append to existing values rather than replace them.

...

```cmake
# CMake 3.21 or later is required for PROJECT_IS_TOP_LEVEL

  option(MYPROJ_ENABLE_TESTING "..." ${PROJECT_IS_TOP_LEVEL})
  if(MYPROJ_ENABLE_TESTING)
      add_subdirectory(tests)
  endif()
  if(PROJECT_IS_TOP_LEVEL)
      add_subdirectory(packaging)
  else()
      # Users are unlikely to be interested in testing this
      # project, so don't show it in the basic options
      mark_as_advanced(MYPROJ_ENABLE_TESTING)
  endif()
```

**Comment by bretbrownjr** [comment]
I'll add that CMake itself needs to evolve better facilities for relevant features at some point. If Beman ends up creating CMake modules to successfully assist in reducing project complexity, we should circle back and open up issues in upstream CMake to illustrate the relevant need.

Beman doesn't exist to innovate in C++ tooling best practices, so if we feel compelled to do that sort of innovation, we should consider it technical debt and develop a plan to unwind it reasonably (perhaps by getting enhancements to CMake itself).

**Comment by ClausKlein** [comment]
> By this I mean CMakeLists.txt should mainly consist of properties unique to this project: names, files, dependencies, directory structure, etc. Logic to behave differently depending on build context is not unique to exemplar. Every project in Beman should not maintain a compatible copy of basically the same CMake logic.

Then you need some `CMake modules` from a central repo to keep the `CMake logic `in sync.

see i.e. https://github.com/aminya/project_options
and https://github.com/MarkSchofield/WindowsToolchain

or maybe: https://github.com/arsenm/sanitizers-cmake

**Comment by camio** [comment]
> But if I add project with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html#id5), I do not want to run its tests or compile the examples!

Projects added with `FetchContent` should not build tests and examples by default, but there are valid uses for turning them on when they are part of a larger project:

1. Someone might want to turn on all tests for a large project, including dependencies, as part of a nightly job or when experimenting with different compiler/flag combinations.
2. Someone may want to make changes to a dependency as part of making changes to a larger project. They could use `FETCHCONTENT_SOURCE_DIR_X` to use a local checkout of the dependency, make changes, and run tests without needing to generate a new project.

The  quoted text in https://github.com/beman-project/exemplar/issues/60#issuecomment-2451396397  has a decent pattern that I think will allow for both use-cases:

```
option(BEMAN_EXEMPLAR_ENABLE_TESTING CACHE BOOL ${PROJECT_IS_TOP_LEVEL) "Build Beman.Exemplar tests")
option(BEMAN_EXEMPLAR_ENABLE_EXAMPLES CACHE BOOL ${PROJECT_IS_TOP_LEVEL) "Build Beman.Exemplar examples")
option(BEMAN_EXEMPLAR_ENABLE_DOCUMENTATION CACHE BOOL ${PROJECT_IS_TOP_LEVEL) "Build Beman.Exemplar documentation")

# ...
```

The only drawback I can think of with this approach is that we aren't honoring the `BUILD_TESTING` variable provided by the [`CTest` module](https://cmake.org/cmake/help/latest/module/CTest.html#module:CTest). I'm beginning to think avoiding the `CTest` module is the right thing to do anyway because the single option it creates isn't granular enough for decently sized projects.
