### ISSUE TITLE
Make build directions work if cut/paste

### ISSUE THREAD

**Issue by steve-downey** [beman-project/exemplar#8]
Currently the notional build directory is `/some/build/dir` , which does not work. Suggest changing to something like
```shell
BUILDDIR=./build
cmake -B $BUILDDIR -S .
cmake --build $BUILDDIR
ctest --test-dir $BUILDDIR  --output-junit build/xunit/results.xml
DESTDIR=./staging cmake --install $BUILDDIR --component libexample-dev --prefix /opt/example
```

which, while having the problem of polluting the tree, do have the advantage of not attempting to write outside the directory I've checked out the example into, and working.

**Comment by neatudarius** [comment]
Please check #15 . Does it work for you?

* Initial section is a template (not copy-pasteable)

![image](https://github.com/user-attachments/assets/9701603f-4baf-405f-bf40-9d0be6c77e6c)

* Then you can expand
![image](https://github.com/user-attachments/assets/72a81d9d-8a55-4cc8-aebd-6fa091f5af17)

I can switch the order if you think it helpe. Please comment on the PR.

**Comment by bretbrownjr** [comment]
@steve-downey Did you want to review the latest state of the README? Or are you happy trusting that the latest pass has addressed your concerns?

**Comment by steve-downey** [comment]
Looks like the current directions work even if I'm being lazy and not reading them.
