### ISSUE TITLE
licenses mismatching with Beman Project License

### ISSUE THREAD

**Issue by dietmarkuehl** [beman-project/exemplar#9]
According to the [Beman Project License](https://github.com/beman-project/beman?tab=License-1-ov-file) the [Beman Project]() is supposed to use an LLVM-modified Apache license. This example repository uses MIT Licenses all over the place. I can't reassign other people copyrights but maybe it would be more reasonable to consistently equip the example repository with an Apache license.

**Comment by neatudarius** [comment]
Changed in #15 .

**Comment by bretbrownjr** [comment]
Looks complete to me
